baseURL = "https://sx.ix5.org/info/"
languageCode = "en-us"
title = "Sony Xperia Corner"
theme = "kube"
Paginate = 20

[permalinks]
    posts = "/post/:slug/"
    docs = "/:slug/"

[params]
    issoURL = "https://comments.ix5.org"
    author = "Felix"
    description = "Information about Sony Xperia devices and AOSP"
    subdescription = "Not in any way affiliated with Sony"

[[menu.main]]
    name = "Docs"
    weight = 1
    url = "/"

[[menu.main]]
    name = "Posts"
    weight = 2
    url = "/posts/"

[[menu.main]]
    name = "About"
    weight = 10
    url = "/about/"

# Needed sice 0.60.0 or so
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      codeFences = true
      guessSyntax = false
      lineNos = false
      noClasses = true
      # See https://xyproto.github.io/splash/docs/all.html
      # and https://github.com/alecthomas/chroma
      style = "pygments"
      tabWidth = 4
